language: node_js
dist: xenial

matrix:
  include:

  - node_js: 12
    env:
      - DB=sqlite3
    before_script:
      - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
    script:
      - fossa init
      - fossa analyze
      - yarn run test

  - node_js: 13
    env:
      - DB=sqlite3
    before_script:
      - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
    script:
      - fossa init
      - fossa analyze
      - yarn run test

  - node_js: 12
    services:
      - postgresql  
    addons:
      postgresql: "11.2"
    before_script:
      - psql -c 'CREATE DATABASE greldal_test;' -U postgres
    env:
      - DB=pg
    script:
      - yarn run test

  - node_js: 13
    services:
      - postgresql
    addons:
      postgresql: "11.2"
    before_script:
      - psql -c 'CREATE DATABASE greldal_test;' -U postgres
    env:
      - DB=pg
    script:
      - yarn run test

  - node_js: 12
    services:
      - mysql
    before_script:
      - mysql -e 'CREATE DATABASE IF NOT EXISTS greldal_test;'
    env:
      - DB=mysql2
    script:
      - yarn run test

  - node_js: 13
    services:
      - mysql
    before_script:
      - mysql -e 'CREATE DATABASE IF NOT EXISTS greldal_test;'
    env:
      - DB=mysql2
    script:
      - yarn run test
